### ISSUE TITLE
mmlspools needs sudo in any case?

### ISSUE THREAD

**Issue by lausser** [theGidy/check_spectrum_scale#5]
Hi,

i have a gpfs installation (4.1.0.5), which i have to monitor. According to the admins pool information is sufficient for them, so all i need to run is the mmlspool command. As you see from the list below, it's not restricted like many other commands, i can run it as the non-privileged monitoring user.
`...
-r-x------    1 root     system         7235 Nov 24 2014  /usr/lpp/mmfs/bin/mmlsnode
-r-xr-xr-x    1 root     system        18467 Nov 24 2014  /usr/lpp/mmfs/bin/mmlsnodeclass
-r-xr-xr-x    1 root     system        26621 Nov 24 2014  /usr/lpp/mmfs/bin/mmlsnsd
-r-xr-xr-x    1 root     system        11014 Nov 24 2014  /usr/lpp/mmfs/bin/mmlspolicy
-r-xr-xr-x    1 root     system        12276 Nov 24 2014  /usr/lpp/mmfs/bin/mmlspool
-r-xr-xr-x    1 root     system         1741 Nov 24 2014  /usr/lpp/mmfs/bin/mmlspv
...
`
My question: is this particular to this installation here or is it the default everywhere else. In this case, would it make sense to remove the sudo prefix in line 386?

Gerhard

**Comment by theGidy** [comment]
I will check this next week. My first guess is, that it is possible to
remove it.

Gerhard Lausser <notifications@github.com> schrieb am Fr., 26. Mai 2017,
13:26:
